import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, AppBar, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Grid, IconButton, Stack, TextField, Toolbar, Typography } from '@mui/material';
import { Copy, ExternalLink, FileText, LogOut, MoreHorizontal, Plus, Share2, Trash2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../store/authStore';
import { useResumeStore } from '../store';
import { createResume, deleteResume, duplicateResume, listResumes, renameResume, shareResume, type CloudResume } from '../services/resumeApi';
import { ApiError } from '../services/api';

const asLocalResume = (item: CloudResume) => ({ ...item.data, id: item.id, title: item.title, template: item.templateId as any, updatedAt: item.updatedAt });

export default function DashboardPage() {
  const navigate = useNavigate(); const user = useAuthStore((state) => state.user); const logout = useAuthStore((state) => state.logout);
  const [resumes, setResumes] = useState<CloudResume[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [rename, setRename] = useState<CloudResume | null>(null); const [renameValue, setRenameValue] = useState(''); const [share, setShare] = useState<CloudResume | null>(null); const [importResume, setImportResume] = useState<any>(null);
  const localResumes = useResumeStore((state) => state.resumes);
  const load = useCallback(async () => { try { setLoading(true); setResumes((await listResumes()).resumes); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load resumes'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => {
    if (loading || importResume) return;
    const pendingId = sessionStorage.getItem('resumeforge_pending_import');
    const dismissedId = sessionStorage.getItem('resumeforge_dismissed_import');
    const pendingResume = pendingId
      ? localResumes.find((item) => item.id === pendingId)
      : !resumes.length ? localResumes.find((item) => item.id !== 'sample-resume' && item.id !== dismissedId) : undefined;
    if (pendingResume) setImportResume(pendingResume);
  }, [loading, resumes.length, localResumes, importResume]);
  const create = async () => { try { const result = await createResume(); navigate(`/resume/${result.resume.id}/edit`); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create resume'); } };
  const remove = async (resume: CloudResume) => { if (!window.confirm('Delete Resume?\n\nThis action cannot be undone.')) return; try { await deleteResume(resume.id); setResumes((items) => items.filter((item) => item.id !== resume.id)); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to delete resume'); } };
  const duplicate = async (resume: CloudResume) => { try { const result = await duplicateResume(resume.id); navigate(`/resume/${result.resume.id}/edit`); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to duplicate resume'); } };
  const submitRename = async () => { if (!rename) return; try { const result = await renameResume(rename.id, renameValue); setResumes((items) => items.map((item) => item.id === rename.id ? result.resume : item)); setRename(null); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to rename resume'); } };
  const toggleShare = async () => { if (!share) return; try { const result = await shareResume(share.id, !share.isPublic); setResumes((items) => items.map((item) => item.id === share.id ? result.resume : item)); setShare(result.resume); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to update sharing'); } };
  const shareUrl = share?.publicSlug ? `${window.location.origin}/r/${share.publicSlug}` : '';
  const sorted = useMemo(() => resumes, [resumes]);
  return <Box sx={{ minHeight: '100vh', bgcolor: '#F7F7F5', color: '#202124' }}>
    <AppBar position="static" elevation={0} sx={{ bgcolor: '#fff', color: '#202124', borderBottom: '1px solid #D0D3D6' }}><Toolbar sx={{ maxWidth: 1180, width: '100%', mx: 'auto' }}><Typography fontWeight={800} fontSize={19}>✦ ResumeForge</Typography><Box flex={1} /><Typography variant="body2" sx={{ mr: 2 }}>{user?.name}</Typography><Button startIcon={<LogOut size={16} />} color="inherit" onClick={() => { logout(); navigate('/login'); }}>Logout</Button></Toolbar></AppBar>
    <Box maxWidth={1180} mx="auto" px={{ xs: 2, sm: 3 }} py={{ xs: 4, sm: 7 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={2} mb={4}><Box><Typography variant="h3" fontWeight={750} letterSpacing="-1.5px">My Resumes</Typography><Typography color="#626871">Create, edit, and share your professional story.</Typography></Box><Button variant="contained" startIcon={<Plus size={18} />} onClick={create}>Create Resume</Button></Stack>{error && <Alert severity="error" sx={{ mb: 3 }} onClose={() => setError('')}>{error}</Alert>}{loading ? <Box textAlign="center" py={8}><CircularProgress color="inherit" /></Box> : sorted.length ? <Grid container spacing={2.5}>{sorted.map((resume) => <Grid item xs={12} sm={6} md={4} key={resume.id}><Card variant="outlined" sx={{ height: '100%', borderColor: '#D0D3D6', bgcolor: '#fff', borderRadius: 2 }}><CardContent sx={{ p: 2.5 }}><Stack direction="row" justifyContent="space-between" alignItems="start"><FileText size={24} /><IconButton size="small"><MoreHorizontal size={18} /></IconButton></Stack><Typography fontWeight={700} mt={2} noWrap>{resume.title}</Typography><Typography variant="caption" color="#626871" display="block">Updated {new Date(resume.updatedAt).toLocaleDateString()}</Typography><Stack direction="row" spacing={1} mt={1.5}><Chip label={resume.templateId} size="small" variant="outlined" /><Chip label={resume.isPublic ? 'Public' : 'Private'} size="small" color={resume.isPublic ? 'success' : 'default'} variant="outlined" /></Stack><Stack direction="row" spacing={1} mt={2} flexWrap="wrap"><Button size="small" onClick={() => navigate(`/resume/${resume.id}/edit`)}>Edit</Button><Button size="small" onClick={() => duplicate(resume)}>Duplicate</Button><Button size="small" onClick={() => { setRename(resume); setRenameValue(resume.title); }}>Rename</Button><Button size="small" color="error" startIcon={<Trash2 size={14} />} onClick={() => remove(resume)}>Delete</Button><Button size="small" startIcon={<Share2 size={14} />} onClick={() => setShare(resume)}>Share</Button></Stack></CardContent></Card></Grid>)}</Grid> : <Card variant="outlined" sx={{ p: 7, textAlign: 'center', borderStyle: 'dashed', bgcolor: 'transparent' }}><Typography variant="h6">Your resume library is empty</Typography><Typography color="#626871" mb={2}>Start with a polished template and make it yours.</Typography><Button variant="contained" onClick={create}>Create your first resume</Button></Card>}</Box>
    <Dialog open={Boolean(rename)} onClose={() => setRename(null)}><DialogTitle>Rename resume</DialogTitle><DialogContent><TextField autoFocus fullWidth label="Resume title" value={renameValue} onChange={(e) => setRenameValue(e.target.value)} sx={{ mt: 1 }} /></DialogContent><DialogActions><Button onClick={() => setRename(null)}>Cancel</Button><Button variant="contained" onClick={submitRename}>Save</Button></DialogActions></Dialog>
    <Dialog open={Boolean(share)} onClose={() => setShare(null)}><DialogTitle>Share Resume</DialogTitle><DialogContent>{share?.isPublic ? <Stack spacing={2} pt={1}><Typography variant="body2">Anyone with this link can view your resume.</Typography><TextField fullWidth value={shareUrl} InputProps={{ readOnly: true }} /><Stack direction="row" spacing={1}><Button startIcon={<Copy size={15} />} onClick={() => navigator.clipboard.writeText(shareUrl)}>Copy link</Button><Button startIcon={<ExternalLink size={15} />} onClick={() => window.open(shareUrl, '_blank')}>Open resume</Button></Stack></Stack> : <Typography py={1}>Public resume unavailable. Enable sharing to create a public link.</Typography>}</DialogContent><DialogActions><Button onClick={() => setShare(null)}>Close</Button><Button variant="contained" onClick={toggleShare}>{share?.isPublic ? 'Disable sharing' : 'Enable sharing'}</Button></DialogActions></Dialog>
    <Dialog open={Boolean(importResume)} onClose={() => setImportResume(null)}><DialogTitle>Resume ready to import</DialogTitle><DialogContent><Typography>Save <strong>{importResume?.title}</strong> to your cloud resume library so you can keep editing it anywhere?</Typography></DialogContent><DialogActions><Button onClick={() => { sessionStorage.removeItem('resumeforge_pending_import'); if (importResume) sessionStorage.setItem('resumeforge_dismissed_import', importResume.id); setImportResume(null); }}>Not now</Button><Button variant="contained" onClick={async () => { try { const result = await createResume({ title: importResume.title, data: importResume, templateId: importResume.template }); setResumes((items) => [result.resume, ...items]); sessionStorage.removeItem('resumeforge_pending_import'); sessionStorage.removeItem('resumeforge_dismissed_import'); setImportResume(null); } catch (e) { setError(e instanceof ApiError ? e.message : 'Unable to import resume'); } }}>Import to My Resumes</Button></DialogActions></Dialog>
  </Box>;
}
